<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BackgroundService-f68fa028-b3e7-4421-843e-177ffdb4b3a2</UserSecretsId>
    <AssemblyName>$(MSAssemblyName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Rules\**" />
    <Content Remove="Rules\**" />
    <EmbeddedResource Remove="Rules\**" />
    <None Remove="Rules\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
  </ItemGroup>
</Project>
