<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-BackgroundService-f68fa028-b3e7-4421-843e-177ffdb4b3a2</UserSecretsId>
		<AssemblyName>$(MSAssemblyName)</AssemblyName>
		<PackageIcon>icon.png</PackageIcon>
		<AssemblyVersion>0.1.0.*</AssemblyVersion>
		<FileVersion>0.1.0.0</FileVersion>
		<PackageVersion>0.1.0</PackageVersion>
		<Title>XLSX Pipeline</Title>
		<Platforms>AnyCPU;ARM64</Platforms>
		<PublishTrimmed>True</PublishTrimmed>
		<PlatformTarget>AnyCPU</PlatformTarget>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<Deterministic>False</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
		<Deterministic>False</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<Deterministic>False</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
		<Deterministic>False</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugType>None</DebugType>
		<DebugSymbols>False</DebugSymbols>
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>XLSXPipeline.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Rules\**" />
		<Content Remove="Rules\**" />
		<EmbeddedResource Remove="Rules\**" />
		<None Remove="Rules\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="itext" Version="9.2.0" />
		<PackageReference Include="itext.bouncy-castle-adapter" Version="9.2.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
		<PackageReference Include="NLog" Version="6.0.2" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.0.2" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Pipelines\**;Examples\**" CopyToPublishDirectory="Never"  />
		<Content Update="Examples\**" CopyToOutputDirectory="Never"  />
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
